name: Build ZMK firmware
on:
  workflow_dispatch:
  push:
    paths:
      - "boards/*"
      - "config/*"

jobs:
  context-info:
    uses: benallred/gha-reference/.github/workflows/context-info.yml@master

  build:
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@main
